{% set name = "hidapi" %}
{% set version = "0.14.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hidapi-{{ version }}.tar.gz
  sha256: 90b773cc4b917e92804153ee55a7a8bab948e51ba72d4838887c83e49ec2bf5f
  patches:
    - fix_include.patch

build:
  script:
    - cythonize hid.pyx
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython <3
    - libudev  # [linux]
    - libusb
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools >=19.0

test:
  imports:
    - hid
    # - hidraw  # [linux]
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trezor/cython-hidapi
  summary: A Cython interface to the hidapi from https://github.com/libusb/hidapi
  license: LicenseRef-cython-hidapi OR GPL-3.0-only OR BSD-3-Clause
  license_file:
    - LICENSE-orig.txt
    - LICENSE-bsd.txt
    - LICENSE-gpl3.txt
    - libusb_hidapi_licenses.txt

extra:
  recipe-maintainers:
    - goanpeca
